@startuml VistaLogica_Nivel2_Limpa
title Vista Lógica - Nível 2 (Contentores)\nSistema de Simulação Clínica AI

skinparam nodesep 70
skinparam ranksep 70
skinparam defaultFontName Arial
skinparam componentStyle rectangle

skinparam interface {
  BackgroundColor #76c7f5
  BorderColor black
}
skinparam component {
  BackgroundColor #76c7f5
  BorderColor black
  FontSize 14
}

interface "UI Profissional de Saúde" as UI_Profissional

component "<<system (C4)>>\nSistema de Simulação Clínica AI" as Sistema {

  component "<<container (C4)>>\nInterface Web (SPA)" as SPA
  component "<<container (C4)>>\nBackend API\n(Orquestrador)" as Backend
  component "<<container (C4)>>\nBase de Dados\nVetorial (RAG)" as VectorDB
  
  interface "API REST" as API_Backend
  interface "Vector API" as API_Vector
  
  API_Backend - Backend
  API_Vector - VectorDB

  
  SPA -right( API_Backend
  Backend -right( API_Vector
}

interface "API do LLM" as API_LLM
Backend -up( API_LLM

UI_Profissional ---> SPA

@enduml